/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edd_drive;

import static edd_drive.Interfaz.hash;
import static edd_drive.Interfaz.pila;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author user
 */
public class JFReportes extends javax.swing.JFrame {

    /**
     * Creates new form JFReportes
     */
    
    //IMAGEN
    ImageIcon imagenHash;
    File miDir;
    JLabel etiqueta;
    JScrollPane scrollpane;
    
    public JFReportes() {
        initComponents();
       
        //IMAGENES
        imagenHash();
        imagenPila();
        imagenAVL();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JBTRegresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        JTPReportes = new javax.swing.JTabbedPane();
        JPHash = new javax.swing.JPanel();
        JSCHash = new javax.swing.JScrollPane();
        JPPila = new javax.swing.JPanel();
        JSCPila = new javax.swing.JScrollPane();
        JPAVL = new javax.swing.JPanel();
        JSCAVL = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JBTRegresar.setText("Regresar");
        JBTRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTRegresarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("REPORTES");

        javax.swing.GroupLayout JPHashLayout = new javax.swing.GroupLayout(JPHash);
        JPHash.setLayout(JPHashLayout);
        JPHashLayout.setHorizontalGroup(
            JPHashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPHashLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JSCHash, javax.swing.GroupLayout.DEFAULT_SIZE, 755, Short.MAX_VALUE)
                .addContainerGap())
        );
        JPHashLayout.setVerticalGroup(
            JPHashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPHashLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JSCHash, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
                .addContainerGap())
        );

        JTPReportes.addTab("HASH", JPHash);

        javax.swing.GroupLayout JPPilaLayout = new javax.swing.GroupLayout(JPPila);
        JPPila.setLayout(JPPilaLayout);
        JPPilaLayout.setHorizontalGroup(
            JPPilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPPilaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JSCPila, javax.swing.GroupLayout.DEFAULT_SIZE, 755, Short.MAX_VALUE)
                .addContainerGap())
        );
        JPPilaLayout.setVerticalGroup(
            JPPilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPPilaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JSCPila, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
                .addContainerGap())
        );

        JTPReportes.addTab("Eventos", JPPila);

        javax.swing.GroupLayout JPAVLLayout = new javax.swing.GroupLayout(JPAVL);
        JPAVL.setLayout(JPAVLLayout);
        JPAVLLayout.setHorizontalGroup(
            JPAVLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPAVLLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JSCAVL, javax.swing.GroupLayout.DEFAULT_SIZE, 755, Short.MAX_VALUE)
                .addContainerGap())
        );
        JPAVLLayout.setVerticalGroup(
            JPAVLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPAVLLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JSCAVL, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
                .addContainerGap())
        );

        JTPReportes.addTab("AVL", JPAVL);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(341, 341, 341)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(360, 360, 360)
                                .addComponent(JBTRegresar)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(JTPReportes)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JBTRegresar)
                .addGap(18, 18, 18)
                .addComponent(JTPReportes)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void imagenHash(){
        miDir = new File(".");
        try {
            
            imagenHash = new ImageIcon(miDir.getCanonicalPath() + "\\HASH.png");
            Image img = imagenHash.getImage();
            ImageIcon imgt = new ImageIcon(img.getScaledInstance(imagenHash.getIconWidth(),imagenHash.getIconHeight(),Image.SCALE_AREA_AVERAGING));
            etiqueta = new JLabel();
            etiqueta.setIcon(imgt);
            JSCHash.setViewportView(etiqueta);
            JPHash.add(JSCHash);
            //scrollpane.setBounds(0, 0, panelHash.getWidth(), panelHash.getHeight());
            
        } catch (IOException ex) {
            System.out.println("Error imagen NO encontrada");
        }
    }
    
    public void imagenPila(){
       miDir = new File(".");
        try {
            
            imagenHash = new ImageIcon(miDir.getCanonicalPath() + "\\Eventos.jpg");
            Image img = imagenHash.getImage();
            ImageIcon imgt = new ImageIcon(img.getScaledInstance(imagenHash.getIconWidth(),imagenHash.getIconHeight(),Image.SCALE_AREA_AVERAGING));
            etiqueta = new JLabel();
            etiqueta.setIcon(imgt);
            JSCPila.setViewportView(etiqueta);
            JPPila.add(JSCPila);
            //scrollpane.setBounds(0, 0, panelHash.getWidth(), panelHash.getHeight());
            
        }catch (IOException ex){
            System.out.println("Error imagen NO encontrada");
        } 
    }
    
    
    public void imagenAVL(){
        miDir = new File(".");
        try {
            
            imagenHash = new ImageIcon(miDir.getCanonicalPath() + "\\AVL.jpg");
            Image img = imagenHash.getImage();
            ImageIcon imgt = new ImageIcon(img.getScaledInstance(imagenHash.getIconWidth(),imagenHash.getIconHeight(),Image.SCALE_AREA_AVERAGING));
            etiqueta = new JLabel();
            etiqueta.setIcon(imgt);
            JSCAVL.setViewportView(etiqueta);
            JPAVL.add(JSCAVL);
            //scrollpane.setBounds(0, 0, panelHash.getWidth(), panelHash.getHeight());
            
        }catch (IOException ex){
            System.out.println("Error imagen NO encontrada");
        } 
    }
    private void JBTRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTRegresarActionPerformed
        this.show(false);
    }//GEN-LAST:event_JBTRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFReportes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBTRegresar;
    private javax.swing.JPanel JPAVL;
    private javax.swing.JPanel JPHash;
    private javax.swing.JPanel JPPila;
    private javax.swing.JScrollPane JSCAVL;
    private javax.swing.JScrollPane JSCHash;
    private javax.swing.JScrollPane JSCPila;
    private javax.swing.JTabbedPane JTPReportes;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
