/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edd_drive;

import Structures.AVL;
import static edd_drive.Interfaz.usuarioActual;
import static edd_drive.Interfaz.usuarioActivo;
import static edd_drive.Interfaz.pila;
import java.awt.Image;
import java.awt.List;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class JFUsuario extends javax.swing.JFrame {

    
    public ArrayList<JButton> carpetas;
    public ArrayList<JButton> archivos;
    public int indice;
    AVL arboltemp;
    /**
     * Creates new form JFUsuario
     * 
     */
    public JFUsuario() {
        initComponents();
        carpetas = new ArrayList<>();
        archivos = new ArrayList<>();
        indice = 0;
        arboltemp = new AVL();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        JBCarCrear = new javax.swing.JButton();
        JBCarModificar = new javax.swing.JButton();
        JBCarEliminar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        JBArCrear = new javax.swing.JButton();
        JBArModificar = new javax.swing.JButton();
        JBArEliminar = new javax.swing.JButton();
        JBArSubir = new javax.swing.JButton();
        JBCarSubir = new javax.swing.JButton();
        JBSalir = new javax.swing.JButton();
        JBCargar = new javax.swing.JButton();
        JBCompartir = new javax.swing.JButton();
        JBDescargar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        JBRegresar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JPArchivos = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Carpetas");

        JBCarCrear.setText("Crear");
        JBCarCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCarCrearActionPerformed(evt);
            }
        });

        JBCarModificar.setText("Modificar");
        JBCarModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCarModificarActionPerformed(evt);
            }
        });

        JBCarEliminar.setText("Eliminar");
        JBCarEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCarEliminarActionPerformed(evt);
            }
        });

        jLabel2.setText("Archivos");

        JBArCrear.setText("Crear");
        JBArCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBArCrearActionPerformed(evt);
            }
        });

        JBArModificar.setText("Modificar");
        JBArModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBArModificarActionPerformed(evt);
            }
        });

        JBArEliminar.setText("Eliminar");
        JBArEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBArEliminarActionPerformed(evt);
            }
        });

        JBArSubir.setText("Subir");
        JBArSubir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBArSubirActionPerformed(evt);
            }
        });

        JBCarSubir.setText("Subir");
        JBCarSubir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCarSubirActionPerformed(evt);
            }
        });

        JBSalir.setText("Salir");
        JBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBSalirActionPerformed(evt);
            }
        });

        JBCargar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/subir2.png"))); // NOI18N
        JBCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCargarActionPerformed(evt);
            }
        });

        JBCompartir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/compartir2.jpg"))); // NOI18N
        JBCompartir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCompartirActionPerformed(evt);
            }
        });

        JBDescargar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/descarga2.png"))); // NOI18N
        JBDescargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBDescargarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Opciones Archivo");

        JBRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/atras2.jpg"))); // NOI18N
        JBRegresar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        JBRegresar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/atras.jpg"))); // NOI18N
        JBRegresar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        JBRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBRegresarActionPerformed(evt);
            }
        });

        JPArchivos.setLayout(new java.awt.GridLayout(0, 3));
        jScrollPane1.setViewportView(JPArchivos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JBCarModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JBCarCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JBCarEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JBArCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JBArModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JBArEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JBArSubir, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JBCarSubir, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JBSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(64, 64, 64)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jLabel3)
                        .addGap(313, 313, 313))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JBCargar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(JBDescargar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JBCompartir, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JBRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(JBSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addComponent(jLabel1))
                            .addComponent(JBRegresar, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(JBCargar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JBCompartir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JBDescargar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JBCarCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JBCarModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JBCarEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(JBCarSubir, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(jLabel2)
                        .addGap(27, 27, 27)
                        .addComponent(JBArCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JBArModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JBArEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JBArSubir, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSalirActionPerformed
        // TODO add your handling code here:
        usuarioActual = "";
        usuarioActivo = null;
        this.show(false);
        
    }//GEN-LAST:event_JBSalirActionPerformed
    //REGRESAR DE DIRECTORIO
    private void JBRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBRegresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBRegresarActionPerformed

    private void JBCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCargarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBCargarActionPerformed

    private void JBDescargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBDescargarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBDescargarActionPerformed
    
    private void JBCompartirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCompartirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBCompartirActionPerformed
    //CARPETA
    private void JBCarCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCarCrearActionPerformed
        // TODO add your handling code here:
        String nombreCarpeta = JOptionPane.showInputDialog("Escribe el nombre de la Carpeta");
        JButton carpeta = new JButton(nombreCarpeta);
        carpeta.setIcon(new ImageIcon(getClass().getResource("/Iconos/carpeta.jpeg")));
        JPArchivos.add(carpeta);
        carpetas.add(carpeta);
        indice++;
        JPArchivos.updateUI();
        pila.push("Creacion de Carpeta",pila.getTime(),usuarioActual);
        pila.getGraphica();
        
    }//GEN-LAST:event_JBCarCrearActionPerformed

    private void JBCarModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCarModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBCarModificarActionPerformed

    private void JBCarEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCarEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBCarEliminarActionPerformed

    private void JBCarSubirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCarSubirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBCarSubirActionPerformed
    //ARCHIVOS
    private void JBArCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBArCrearActionPerformed
        // TODO add your handling code here:
        String nombreArchivo = JOptionPane.showInputDialog("Escribe el nombre del Archivo");
        String contenidoArchivo = JOptionPane.showInputDialog("Escribe el Contenido del Archivo");
        String timesTamp = pila.getTime();
        arboltemp.insertar(nombreArchivo, contenidoArchivo, timesTamp, usuarioActual);
        JButton archivo = new JButton(nombreArchivo);
        archivo.setIcon(new ImageIcon(getClass().getResource("/Iconos/archivo.png")));
        JPArchivos.add(archivo);
        archivos.add(archivo);
        indice++;
        JPArchivos.updateUI();
        pila.push("Creacion de Archivo",pila.getTime(),usuarioActual);
        pila.getGraphica();
        arboltemp.getGrafica();
    }//GEN-LAST:event_JBArCrearActionPerformed

    private void JBArModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBArModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBArModificarActionPerformed

    private void JBArEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBArEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBArEliminarActionPerformed

    private void JBArSubirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBArSubirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBArSubirActionPerformed
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBArCrear;
    private javax.swing.JButton JBArEliminar;
    private javax.swing.JButton JBArModificar;
    private javax.swing.JButton JBArSubir;
    private javax.swing.JButton JBCarCrear;
    private javax.swing.JButton JBCarEliminar;
    private javax.swing.JButton JBCarModificar;
    private javax.swing.JButton JBCarSubir;
    private javax.swing.JButton JBCargar;
    private javax.swing.JButton JBCompartir;
    private javax.swing.JButton JBDescargar;
    private javax.swing.JButton JBRegresar;
    private javax.swing.JButton JBSalir;
    private javax.swing.JPanel JPArchivos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
